<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MongoDB.Driver" Version="3.8.1" />
    <PackageReference Include="SharpCompress" Version="0.37.2" />
    <PackageReference Include="StackExchange.Redis" Version="2.13.1" />
    <PackageReference Include="ZiggyCreatures.FusionCache" Version="2.6.0" />
    <PackageReference Include="ZiggyCreatures.FusionCache.Serialization.NewtonsoftJson" Version="2.6.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Modules\Social\Combince.Modules.Social.Infrastructure\Combince.Modules.Social.Infrastructure.csproj" />
    <ProjectReference Include="..\..\Modules\Users\Combince.Modules.Users.Infrastructure\Combince.Modules.Users.Infrastructure.csproj" />
    <ProjectReference Include="..\Combince.Shared.Core\Combince.Shared.Core.csproj" />
  </ItemGroup>

</Project>
